apiVersion: apps/v1
kind: Deployment
metadata:
  name: utc-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gad0788/dev-alex-img:4.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "400m"
          requests:
            memory: "250Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: utc-svc
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 80
      # optional
      nodePort: 30008